config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  get "/home", to: "pages#home"
  get "/projects", to: "pages#projects"
  get "/contact", to: "pages#contact"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def projects
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortafolioGithubIo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Se agregan fonts desde Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Geologica:wght@700&family=Montserrat:wght@300&display=swap" rel="stylesheet">
    <!-- Se agrega CDN Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <!-- Se agrega CDN Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <!-- Se agrega Menu -->
    <nav>
      <nav class="navbar navbar-expand-lg bg-dark border-bottom border-bottom-dark" data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">Portafolio</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
              <li class="nav-item">
              <%= link_to "Home", "/", class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "projects", projects_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "contact", contact_path, class: "nav-link" %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </nav>


    <!-- Se agrega clase container a yield -->
    <div class="container">
      <%= yield %>
    </div>
    <!-- Se agrega CDN Bootstrap js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>

  <!-- Se agrega footer -->
  <footer class="mt-5 text-white text-center" style="background-color: #191e24; height: 60px">
    <p class="pt-2">"La simplicidad llevada al extremo, se convierte en elegancia."(Jhon Franklin)</p>
  </footer>

</html>

app/views/pages/contact.html.erb
<h1 class="text-center mt-3">Contacto</h1>
<p class="card-text">Si tienes alguna pregunta o necesitas más información, no dudes en contactarme. Estoy emocionado por compartir mi conocimiento y trabajar en futuros proyectos. ¡Gracias por tu atención!</p>

<!-- Se agrega formulario de contacto -->
<form class="row g-3">
    <div class="col-md-6">
      <label for="inputNombre" class="form-label">Nombre</label>
      <input type="text" class="form-control" id="inputNombre">
    </div>
    <div class="col-md-6">
      <label for="inputApellidos" class="form-label">Apellidos</label>
      <input type="text" class="form-control" id="inputApellidos">
    </div>
    <div class="col-12">
      <label for="inputEmail" class="form-label">Email</label>
      <input type="email" class="form-control" id="inputEmail">
    </div>
    <div class="col-md-6">
      <label for="inputCelular" class="form-label">Celular</label>
      <input type="text" class="form-control" id="inputCelular" placeholder="+(569 cod.Páis) número">
    </div>
    <div class="col-md-6">
      <label for="inputMotivo" class="form-label">Motivo</label>
      <select id="inputMotivo" class="form-select">
        <option selected>Quiero un Proyecto Web desde 0</option>
        <option>Quiero actualizar mi Sitio Web</option>
        <option>Quiero una asesoria</option>
        <option>Contacto</option>
        <option>Otros..</option>
      </select>
    </div>
    <div class="col-12">
        <label for="inputMensaje" class="form-label">Mensaje</label>
        <textarea class="form-control" id="inputMensaje" placeholder="Escribe tu mensaje.." rows="5"></textarea>
      </div>
    <div class="col-12">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" id="gridCheck">
        <label class="form-check-label" for="gridCheck">
          No soy un Robot
        </label>
      </div>
    </div>
    <div class="col-12">
      <button type="submit" class="btn btn-primary">Enviar</button>
    </div>
  </form>

app/views/pages/home.html.erb
<h1 class="text-center mt-3">Portafolio</h1>

<!-- Se agrega tarjeta con datos personales -->
<div class="card mt-3 mb-3" style="max-width: 100%;">
    <div class="row g-0">
        <div class="col-md-4 pt-3">
            <%= image_tag 'user.png', class: 'profile_img'%>
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">Paul Rojas Calderón</h5>
                <p class="card-text">Ingeniero en Informática <br> Apasionado por el desarrollo web y la programación. Mi objetivo es crear soluciones tecnológicas innovadoras y funcionales que mejoren la experiencia del usuario.</p>
                <p class="card-text">Actualmente me encuentro estudiando Ruby on Rails y JavaScript, dos tecnologías ampliamente utilizadas en el desarrollo web. Estoy emocionado por expandir mis habilidades y aplicarlas en proyectos desafiantes.</p>
                <p class="card-text">Sígueme en las RRSS para no perderte las novedades de mis desarrollos:</p>
                <p class="card-text"><i class="fa-brands fa-github fa-3x me-3"></i><i
                        class="fa-brands fa-linkedin fa-3x me-3"></i><i class="fa-brands fa-instagram fa-3x me-3"></i><i
                        class="fa-brands fa-twitter fa-3x me-3"></i></p>
                <p class="card-text"><small class="text-muted">Last updated 3
                        mins ago</small></p>
            </div>
        </div>
    </div>
</div>

<!-- Barra de Skills -->
<div class="mt-5 pb-5" style="background-color: #191e24;">
    <h2 class="text-center text-white pt-2">SKILLS</h2>
    <p class="ms-4 text-white">Ruby on Rails</p>
    <div class="progress mx-4" role="progressbar" aria-label="Animated striped example" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100">
        <div class="progress-bar progress-bar-striped progress-bar-animated" style="width: 40%"></div>
    </div>
    <p class="mt-2 ms-4 text-white">Javascript</p>
    <div class="progress mx-4" role="progressbar" aria-label="Animated striped example" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
        <div class="progress-bar progress-bar-striped progress-bar-animated" style="width: 20%"></div>
    </div>
    <p class="mt-2 ms-4 text-white">HTML</p>
    <div class="progress mx-4" role="progressbar" aria-label="Animated striped example" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">
        <div class="progress-bar progress-bar-striped progress-bar-animated" style="width: 50%"></div>
    </div>
    <p class="mt-2 ms-4 text-white">CSS</p>
    <div class="progress mx-4" role="progressbar" aria-label="Animated striped example" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">
        <div class="progress-bar progress-bar-striped progress-bar-animated" style="width: 50%"></div>
    </div>
</div>

app/views/pages/projects.html.erb
<h1 class="text-center mt-3">Proyectos</h1>

<p class="card-text">Algunos proyectos que he realizado utilizando HTML5, CSS3 y Bootstrap, demostrando mis habilidades en el diseño y desarrollo frontend</p>
<!-- Tarjetas Proyectos -->
<div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        <div class="col">
            <div class="card h-100" style="width: 18rem;">
                <%= image_tag 'card1.png', class: 'card-img-top'%>
                <div class="card-body">
                    <h5 class="card-title">Meet&Coffe</h5>
                    <p class="card-text">Maquetación de Sitio Web con HTML5 y Estilos con CSS3, creación de menú y posicionamiento de imagenes</p>
                    <a href="#" class="btn btn-primary">Ver más</a>
                </div>
            </div>
        </div>

        <div class="col">
            <div class="card h-100" style="width: 18rem;">
                <%= image_tag 'card2.png', class: 'card-img-top'%>
                <div class="card-body">
                    <h5 class="card-title">Suricata</h5>
                    <p class="card-text">Maquetación de Sitio Web Responsivo utilizando Framework Bootstrap e implemantación de Cards</p>
                    <a href="#" class="btn btn-primary">Ver más</a>
                </div>
            </div>
        </div>

        <div class="col">
            <div class="card h-100" style="width: 18rem;">
                <%= image_tag 'card3.png', class: 'card-img-top'%>
                <div class="card-body">
                    <h5 class="card-title">Cuppon</h5>
                    <p class="card-text">Maquetación de Sitio Web Responsivo utilizando Framework Bootstrap e implemantación de Cards</p>
                    <a href="#" class="btn btn-primary">Ver más</a>
                </div>
            </div>
        </div>
    </div>
</div>